package com.admom.mygreendaotest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.group.dongdong.beans.DayUser;
import com.example.group.dongdong.beans.TotalUser;

import com.admom.mygreendaotest.DayUserDao;
import com.admom.mygreendaotest.TotalUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayUserDaoConfig;
    private final DaoConfig totalUserDaoConfig;

    private final DayUserDao dayUserDao;
    private final TotalUserDao totalUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayUserDaoConfig = daoConfigMap.get(DayUserDao.class).clone();
        dayUserDaoConfig.initIdentityScope(type);

        totalUserDaoConfig = daoConfigMap.get(TotalUserDao.class).clone();
        totalUserDaoConfig.initIdentityScope(type);

        dayUserDao = new DayUserDao(dayUserDaoConfig, this);
        totalUserDao = new TotalUserDao(totalUserDaoConfig, this);

        registerDao(DayUser.class, dayUserDao);
        registerDao(TotalUser.class, totalUserDao);
    }
    
    public void clear() {
        dayUserDaoConfig.clearIdentityScope();
        totalUserDaoConfig.clearIdentityScope();
    }

    public DayUserDao getDayUserDao() {
        return dayUserDao;
    }

    public TotalUserDao getTotalUserDao() {
        return totalUserDao;
    }

}
